name: ETL Pipelines

on: [push]
# on:
#   push:
#     branches:
#       - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.poetry/bin:$PATH"
          poetry --version
        shell: bash

      - name: Install project dependencies
        run: |
          poetry install
        working-directory: rag-pipeline-chatbot

      - name: Run Prices ETL
        run: poetry run python src/etl/gold_prices_etl.py
        working-directory: rag-pipeline-chatbot

      - name: Run News ETL
        run: poetry run python src/etl/gold_news_etl.py
        working-directory: rag-pipeline-chatbot
